/**
 * Main generator that produces Zod schema files from proto files
 *
 * The schemas validate the ts-proto shape of a message (the objects ts-proto encodes and
 * decodes) and accept exactly what protovalidate accepts on the wire:
 *
 * - an absent property of an implicit-presence field stands for its proto3 zero value, so it
 *   is optional only when that zero value passes every rule of the field;
 * - message-level CEL rules, oneof rules and CEL rules of implicit-presence fields run in a
 *   `.superRefine()` on the object;
 * - a rule the generator cannot translate faithfully fails the generation.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { Schema, GeneratedFile } from "@bufbuild/protoplugin";
import type { DescFile, DescMessage, DescEnum, DescField } from "@bufbuild/protobuf";
import { ScalarType } from "@bufbuild/protobuf";
import { mapFieldToZod, mapListItemToZod, type TypeMapperContext, type ZodTypeInfo } from "./type-mapper.js";
import {
  checkAccepts,
  fieldPlan,
  Ignore,
  is64BitScalar,
  messagePlan,
  oneofRequired,
  zeroTest,
  zeroValue,
  type Check,
  type CelRuleSpec,
  type ValueKind,
  UnsupportedRuleError,
} from "./validation/rules.js";
import { compileCelRule, rawToCel, CelUnsupportedError, presenceOf, type Compiled } from "./validation/cel/compiler.js";
import { toSchemaName, getRelativeImportPath, toScreamingSnakeCase, stripEnumPrefix, tsProtoFieldName } from "./utils.js";

export interface PluginOptions {
  /** Whether to include Response messages (usually not needed for form validation) */
  includeResponses: boolean;
}

/** Output path of the runtime helpers shared by every generated file */
const RUNTIME_FILE = "zod_rules";

/**
 * Main entry point for generating Zod schemas
 */
export function generateZodSchemas(
  schema: Schema<PluginOptions>
): void {
  let generated = false;
  for (const file of schema.files) {
    // Skip third-party dependencies - only generate for local proto files
    if (file.name.startsWith("buf/") || file.name.startsWith("google/")) {
      continue;
    }
    generated = generateFileSchemas(schema, file) || generated;
  }
  if (generated) {
    const f = schema.generateFile(`${RUNTIME_FILE}.ts`);
    f.print("// @generated by protoc-gen-zod: runtime helpers of the *_zod.ts schemas");
    f.print(fs.readFileSync(runtimeSourcePath(), "utf8").trimEnd());
  }
}

/** The runtime helpers are emitted from their TypeScript source, next to the compiled plugin */
function runtimeSourcePath(): string {
  const candidate = path.resolve(__dirname, "..", "src", "runtime", "zod_rules.ts");
  if (!fs.existsSync(candidate)) {
    throw new Error(`protoc-gen-zod: runtime source not found at ${candidate}`);
  }
  return candidate;
}

/**
 * Generates Zod schemas for a single proto file; returns whether a file was written
 */
function generateFileSchemas(
  schema: Schema<PluginOptions>,
  file: DescFile
): boolean {
  // Filter messages first to check if we have anything to generate
  const messages = file.messages.filter((msg) => {
    // Skip Response messages unless option is set
    if (!schema.options.includeResponses && msg.name.endsWith("Response")) {
      return false;
    }
    return true;
  });

  const localEnums = file.enums;

  // Skip generating file if there are no messages or enums to export
  if (messages.length === 0 && localEnums.length === 0) {
    return false;
  }

  // Preserve directory structure: mirai/v1/auth -> mirai/v1/auth_zod.ts
  // Note: file.name excludes the .proto suffix
  const outputFileName = `${file.name}_zod.ts`;

  const context: TypeMapperContext = {
    currentProtoPath: file.name,
  };

  // The body is built first: the imports depend on what it uses
  const body: string[] = [];
  const imports = new Map<string, Set<string>>();
  const addImport = (info: ZodTypeInfo) => {
    if (info.needsImport) {
      const existing = imports.get(info.needsImport.from) ?? new Set();
      existing.add(info.needsImport.name);
      imports.set(info.needsImport.from, existing);
    }
  };

  // Local enums need to be imported for z.enum to work
  // ts-proto generates files with .js suffix for ES modules
  const pbImportPath = getRelativeImportPath(file.name, file.name, ".js");
  for (const enumDesc of localEnums) {
    const existing = imports.get(pbImportPath) ?? new Set();
    existing.add(enumDesc.name);
    imports.set(pbImportPath, existing);
  }

  // Generate enum schemas for enums defined in this file
  for (const enumDesc of localEnums) {
    generateEnumSchema(body, enumDesc);
  }

  // Generate message schemas
  // Sort by dependency order and identify recursive types
  const { sortedMessages, recursiveTypes } = analyzeMessageDependencies(messages, file.name);

  for (const message of sortedMessages) {
    generateMessageSchema(body, message, context, recursiveTypes, addImport);
    body.push("");
  }

  const f = schema.generateFile(outputFileName);

  // Add file header
  f.print(`// @generated from file ${file.name}.proto`);
  f.print("/* eslint-disable */");
  f.print();

  // Write zod import
  f.print('import { z } from "zod";');
  if (body.some((line) => line.includes("__r."))) {
    f.print(`import * as __r from "${getRelativeImportPath(file.name, RUNTIME_FILE, ".js")}";`);
  }

  // Write imports from *_pb.ts files (for enums)
  for (const [importPath, names] of imports) {
    const sortedNames = Array.from(names).sort();
    f.print(`import { ${sortedNames.join(", ")} } from "${importPath}";`);
  }

  f.print();
  for (const line of body) {
    f.print(line);
  }
  return true;
}

/**
 * Generates a Zod schema for an enum
 */
function generateEnumSchema(
  out: string[],
  enumDesc: DescEnum
): void {
  const enumName = enumDesc.name;
  const schemaName = toSchemaName(enumName);
  const screaming = toScreamingSnakeCase(enumName);

  // Add JSDoc
  out.push("/**");
  out.push(` * Zod schema for ${enumName} enum`);
  if (enumDesc.deprecated) {
    out.push(" * @deprecated");
  }
  out.push(` * @generated from enum ${enumDesc.typeName}`);
  out.push(" */");

  // Enum is already imported at the top of the file
  out.push(`export const ${schemaName} = z.enum(${enumName});`);
  out.push(`export type ${enumName}Type = z.infer<typeof ${schemaName}>;`);
  out.push("");

  // Generate number to string map
  out.push("/**");
  out.push(` * Map of ${enumName} enum values to string representations`);
  out.push(` * @generated from enum ${enumDesc.typeName}`);
  out.push(" */");
  out.push(`export const ${screaming}_MAP: Record<number, string> = {`);
  for (const value of enumDesc.values) {
    const strippedName = stripEnumPrefix(value.name, enumName);
    out.push(`  ${value.number}: "${strippedName}",`);
  }
  out.push("};");
  out.push("");

  // Generate string to enum map (excluding UNSPECIFIED)
  out.push("/**");
  out.push(` * Map of string representations to ${enumName} enum values`);
  out.push(` * @generated from enum ${enumDesc.typeName}`);
  out.push(" */");
  out.push(`export const STRING_TO_${screaming}: Record<string, ${enumName}> = {`);
  for (const value of enumDesc.values) {
    // Skip UNSPECIFIED (value 0) for the reverse map
    if (value.number === 0) continue;
    const strippedName = stripEnumPrefix(value.name, enumName);
    out.push(`  ${strippedName}: ${enumName}.${value.name},`);
  }
  out.push("};");
  out.push("");
}

/** A property of a message schema, and the object-level statements it needs */
interface FieldEmission {
  key: string;
  zod: string;
  optional: boolean;
  statements: string[];
}

/**
 * Generates a Zod schema for a message
 */
function generateMessageSchema(
  out: string[],
  message: DescMessage,
  context: TypeMapperContext,
  recursiveTypes: Set<string>,
  addImport: (info: ZodTypeInfo) => void
): void {
  const schemaName = toSchemaName(message.name);
  const isRecursive = recursiveTypes.has(message.name);

  const plan = messagePlan(message);
  const inMessageOneof = new Set(plan.oneofRules.flatMap((r) => r.fields.map((f) => f.name)));
  const fields = message.fields.map((field) =>
    emitField(field, context, recursiveTypes, addImport, inMessageOneof.has(field.name))
  );

  // Object-level checks: CEL of implicit-presence fields, oneofs, message rules
  const statements: string[] = fields.flatMap((f) => f.statements);
  for (const oneof of message.oneofs) {
    const members = oneof.fields.map((f) => JSON.stringify(tsProtoFieldName(f.name)));
    statements.push(`__r.oneof(ctx, v, ${JSON.stringify(oneof.name)}, [${members.join(", ")}], ${oneofRequired(oneof)});`);
  }
  for (const rule of plan.oneofRules) {
    const names = rule.fields.map((f) => f.name).join(", ");
    const set = rule.fields.map((f) => presenceOf("v", f));
    statements.push(`__r.messageOneof(ctx, ${JSON.stringify(names)}, ${rule.required}, [${set.join(", ")}]);`);
  }
  for (const rule of plan.cel) {
    statements.push(celStatement(rule, "v", { js: "v", type: { k: "message", desc: message } }, message.typeName));
  }

  // Add JSDoc
  out.push("/**");
  out.push(` * Zod schema for ${message.name}`);
  if (message.deprecated) {
    out.push(" * @deprecated");
  }
  out.push(` * @generated from message ${message.typeName}`);
  out.push(" */");

  const objectLines: string[] = [];
  for (const [i, field] of fields.entries()) {
    if (message.fields[i].deprecated) {
      objectLines.push(`  /** @deprecated */`);
    }
    objectLines.push(`  ${field.key}: ${field.zod},`);
  }
  const refine = statements.length > 0
    ? ["}).superRefine((v, ctx) => {", ...statements.map((s) => `  ${s}`), "})"]
    : ["})"];

  if (isRecursive) {
    // For recursive types, we need to use z.lazy() with explicit type annotation
    out.push(`export type ${message.name} = {`);
    for (const [i, field] of fields.entries()) {
      out.push(`  ${field.key}${field.optional ? "?" : ""}: ${inferTsType(message.fields[i])};`);
    }
    out.push("};");
    out.push("");
    out.push(`export const ${schemaName}: z.ZodType<${message.name}> = z.lazy(() => z.object({`);
    out.push(...objectLines);
    out.push(...refine.slice(0, -1), `${refine[refine.length - 1]});`);
  } else {
    out.push(`export const ${schemaName} = z.object({`);
    out.push(...objectLines);
    out.push(...refine.slice(0, -1), `${refine[refine.length - 1]};`);

    // Export inferred type
    out.push("");
    out.push(`export type ${message.name} = z.infer<typeof ${schemaName}>;`);
  }
}

/** Emits one `.refine()` per check */
function refines(checks: Check[]): string {
  return checks
    .map((c) => `.refine((v) => ${c.pred}, { message: ${JSON.stringify(`${c.id}: ${c.message}`)}${c.abort ? ", abort: true" : ""} })`)
    .join("");
}

/** Wraps a check so that it passes on the zero value (ignore = IGNORE_IF_ZERO_VALUE) */
function skipZero(check: Check, zero: string): Check {
  return { ...check, pred: `(${zero}) || (${check.pred})` };
}

/** Compiles a CEL rule into a `__r.cel(...)` statement over the given value */
function celStatement(
  rule: CelRuleSpec,
  valueJs: string,
  self: Compiled,
  where: string,
  guard?: string,
  pathKey?: string
): string {
  let compiled;
  try {
    compiled = compileCelRule(rule.expression, self);
  } catch (err) {
    if (err instanceof CelUnsupportedError) {
      throw new UnsupportedRuleError(where, `CEL rule '${rule.id}' (${rule.expression}): ${err.message}`);
    }
    throw err;
  }
  const message = rule.message || (compiled.resultType === "bool" ? `"${rule.expression}" returned false` : "");
  const predicate = guard ? `(${guard}) || ${compiled.js}` : compiled.js;
  const pathArg = pathKey ? `, [${JSON.stringify(pathKey)}]` : "";
  return `__r.cel(ctx, ${valueJs}, (v: any) => ${predicate}, ${JSON.stringify(rule.id)}, ${JSON.stringify(message)}${pathArg});`;
}

/** Field-level CEL rules on a value, as a `.superRefine()` chained on its schema */
function celRefine(rules: CelRuleSpec[], self: Compiled, where: string, guard?: string): string {
  if (rules.length === 0) return "";
  const statements = rules.map((r) => celStatement(r, "v", self, where, guard));
  return `.superRefine((v, ctx) => { ${statements.join(" ")} })`;
}

function valueKindOf(field: DescField): ValueKind | undefined {
  if (field.fieldKind === "scalar") return { scalar: field.scalar };
  if (field.fieldKind === "enum") return { enumDesc: field.enum };
  if (field.fieldKind === "list" && field.listKind === "scalar") return { scalar: field.scalar };
  if (field.fieldKind === "list" && field.listKind === "enum") return { enumDesc: field.enum };
  return undefined;
}

function hasCheck(checks: Check[], suffix: string): boolean {
  return checks.some((c) => c.id.endsWith(suffix));
}

/** Reference to a message schema, lazy when the message is recursive */
function messageRef(zodType: string, refMsgName: string, recursiveTypes: Set<string>): string {
  return recursiveTypes.has(refMsgName) ? `z.lazy(() => ${toSchemaName(refMsgName)})` : zodType;
}

/**
 * Builds the schema of a single field from its rules and its presence
 */
function emitField(
  field: DescField,
  context: TypeMapperContext,
  recursiveTypes: Set<string>,
  addImport: (info: ZodTypeInfo) => void,
  inMessageOneof: boolean
): FieldEmission {
  const key = tsProtoFieldName(field.name);
  const where = `${field.parent.typeName}.${field.name}`;
  const plan = fieldPlan(field);
  // A field named by a (buf.validate.message).oneof rule ignores its zero value by default
  const ignore = !plan.ignoreSet && inMessageOneof ? Ignore.IF_ZERO_VALUE : plan.ignore;
  const kind = valueKindOf(field);

  const typeInfo = mapFieldToZod(field, context, {
    finite: hasCheck(plan.checks, ".finite"),
    definedOnly: hasCheck(plan.checks, "enum.defined_only"),
  });
  addImport(typeInfo);

  const result = (zod: string, optional: boolean, statements: string[] = []): FieldEmission => ({
    key,
    zod: optional ? `${zod}.optional()` : zod,
    optional,
    statements,
  });

  switch (field.fieldKind) {
    case "scalar":
    case "enum": {
      const k = kind!;
      const zero = zeroTest(k);
      const explicit = field.oneof !== undefined || field.proto.proto3Optional;
      if (explicit) {
        // Set or unset: the rules apply to any set value, the zero value included
        const zod = typeInfo.zodType + refines(plan.checks) + celRefine(plan.cel, rawToCel("v", kindForCel(field)), where);
        return result(zod, !plan.required);
      }
      const checks = ignore === Ignore.IF_ZERO_VALUE ? plan.checks.map((c) => skipZero(c, zero)) : [...plan.checks];
      if (plan.required) {
        checks.unshift({ id: "required", message: "value is required", pred: `!(${zero})`, abort: true });
      }
      const zeroValid = checks.every((c) => checkAccepts(c, zeroValue(k)));
      // An absent property is the zero value: CEL rules read it with its default, at object level
      const zeroJs = kind!.scalar === ScalarType.BYTES ? "__r.EMPTY_BYTES" : JSON.stringify(zeroValue(k));
      const statements = plan.cel.map((r) =>
        celStatement(r, `v.${key} ?? ${zeroJs}`, rawToCel("v", kindForCel(field)), where, ignore === Ignore.IF_ZERO_VALUE ? zero : undefined, key)
      );
      return result(typeInfo.zodType + refines(checks), zeroValid, statements);
    }

    case "message": {
      const base = messageRef(typeInfo.zodType, field.message.name, recursiveTypes);
      const zod = base + celRefine(plan.cel, rawToCel("v", { message: field.message }), where);
      return result(zod, !plan.required);
    }

    case "list": {
      const items = plan.items;
      const itemInfo = mapListItemToZod(field, context, {
        finite: hasCheck(items?.checks ?? [], ".finite"),
        definedOnly: hasCheck(items?.checks ?? [], "enum.defined_only"),
      });
      addImport(itemInfo);
      let item = field.listKind === "message" ? messageRef(itemInfo.zodType, field.message.name, recursiveTypes) : itemInfo.zodType;
      if (items) {
        const itemZero = kind && items.ignore === Ignore.IF_ZERO_VALUE ? zeroTest(kind) : undefined;
        item += refines(itemZero ? items.checks.map((c) => skipZero(c, itemZero)) : items.checks);
        item += celRefine(items.cel, rawToCel("v", kindForCel(field)), `${where}[]`, itemZero);
      }
      const empty = "v.length === 0";
      const checks = ignore === Ignore.IF_ZERO_VALUE ? plan.checks.map((c) => skipZero(c, empty)) : [...plan.checks];
      if (plan.required) {
        checks.unshift({ id: "required", message: "value is required", pred: `!(${empty})`, abort: true });
      }
      const emptyValid = checks.every((c) => checkAccepts(c, []));
      const statements = plan.cel.map((r) =>
        celStatement(r, `v.${key} ?? []`, rawToCel("v", { ...kindForCel(field), list: true }), where, ignore === Ignore.IF_ZERO_VALUE ? empty : undefined, key)
      );
      return result(`z.array(${item})${refines(checks)}`, emptyValid, statements);
    }

    case "map": {
      const checks: Check[] = plan.required
        ? [{ id: "required", message: "value is required", pred: "Object.keys(v).length > 0" }]
        : [];
      return result(typeInfo.zodType + refines(checks), !plan.required);
    }
  }
}

/** Describes a field value (or a list item) for rawToCel */
function kindForCel(field: DescField): Parameters<typeof rawToCel>[1] {
  switch (field.fieldKind) {
    case "scalar":
      return { scalar: field.scalar };
    case "enum":
      return { isEnum: true };
    case "message":
      return { message: field.message };
    case "list":
      return field.listKind === "scalar"
        ? { scalar: field.scalar }
        : field.listKind === "enum"
          ? { isEnum: true }
          : { message: field.message };
    case "map":
      throw new Error("maps have no CEL value kind");
  }
}

/**
 * Infers the TypeScript type of a field in ts-proto shape (used for recursive type declarations)
 */
function inferTsType(field: DescField): string {
  const scalarType = (scalar: ScalarType): string => {
    switch (scalar) {
      case ScalarType.STRING:
        return "string";
      case ScalarType.BOOL:
        return "boolean";
      case ScalarType.BYTES:
        return "Uint8Array";
      default:
        return is64BitScalar(scalar) ? "string" : "number";
    }
  };
  const messageType = (msg: DescMessage): string => {
    switch (msg.typeName) {
      case "google.protobuf.Timestamp":
        return "Date";
      case "google.protobuf.Struct":
        return "Record<string, any>";
      case "google.protobuf.Value":
        return "any";
      case "google.protobuf.ListValue":
        return "any[]";
      default:
        return msg.name;
    }
  };
  switch (field.fieldKind) {
    case "scalar":
      return scalarType(field.scalar);
    case "enum":
      return field.enum.name;
    case "message":
      return messageType(field.message);
    case "list":
      return `${field.listKind === "scalar" ? scalarType(field.scalar) : field.listKind === "enum" ? field.enum.name : messageType(field.message)}[]`;
    case "map":
      return `Record<string, ${field.mapKind === "scalar" ? scalarType(field.scalar) : field.mapKind === "enum" ? field.enum.name : messageType(field.message)}>`;
  }
}

/**
 * Analyzes message dependencies and returns sorted list plus recursive types
 */
interface DependencyAnalysis {
  sortedMessages: DescMessage[];
  recursiveTypes: Set<string>;
}

function analyzeMessageDependencies(
  messages: readonly DescMessage[],
  currentProtoPath: string
): DependencyAnalysis {
  const messageNames = new Set(messages.map((m) => m.name));
  // Map: message name -> messages it depends on (references)
  const dependencies = new Map<string, Set<string>>();
  const recursiveTypes = new Set<string>();

  // Initialize dependencies
  for (const msg of messages) {
    dependencies.set(msg.name, new Set());
  }

  // Build dependency graph (for messages in the same file)
  for (const msg of messages) {
    for (const field of msg.fields) {
      if (field.fieldKind === "message") {
        const refMsgName = field.message.name;
        if (messageNames.has(refMsgName) && field.message.file.name === currentProtoPath) {
          // msg depends on refMsgName (msg references refMsgName)
          dependencies.get(msg.name)!.add(refMsgName);

          // Check for self-reference (recursive type)
          if (refMsgName === msg.name) {
            recursiveTypes.add(msg.name);
          }
        }
      } else if (field.fieldKind === "list" && field.listKind === "message") {
        const refMsgName = field.message.name;
        if (messageNames.has(refMsgName) && field.message.file.name === currentProtoPath) {
          dependencies.get(msg.name)!.add(refMsgName);

          if (refMsgName === msg.name) {
            recursiveTypes.add(msg.name);
          }
        }
      }
    }
  }

  // Detect cycles (multi-step recursion)
  for (const msgName of messageNames) {
    if (hasCycle(msgName, dependencies, new Set())) {
      recursiveTypes.add(msgName);
    }
  }

  // Kahn's algorithm - remove self-loops for sorting purposes
  const inDegree = new Map<string, number>();
  for (const msg of messages) {
    inDegree.set(msg.name, 0);
  }

  for (const [msgName, deps] of dependencies) {
    for (const dep of deps) {
      if (dep !== msgName && !recursiveTypes.has(dep)) {
        // Don't count self-references or references to recursive types
        inDegree.set(dep, (inDegree.get(dep) ?? 0) + 1);
      }
    }
  }

  // Start with messages that are not referenced by others (leaves)
  // Actually we need the opposite - start with messages that don't depend on others
  const result: DescMessage[] = [];
  const visited = new Set<string>();
  const queue: string[] = [];

  // Find messages with no dependencies (except self-refs and recursive)
  for (const msg of messages) {
    const deps = dependencies.get(msg.name)!;
    const nonSelfDeps = Array.from(deps).filter(d => d !== msg.name && !recursiveTypes.has(d));
    if (nonSelfDeps.length === 0) {
      queue.push(msg.name);
    }
  }

  while (queue.length > 0) {
    const name = queue.shift()!;
    if (visited.has(name)) continue;
    visited.add(name);

    const msg = messages.find((m) => m.name === name)!;
    result.push(msg);

    // Find messages that depend on this one and now have all deps satisfied
    for (const [otherName, deps] of dependencies) {
      if (visited.has(otherName)) continue;
      if (deps.has(name)) {
        // Check if all non-recursive deps are now satisfied
        const nonSelfDeps = Array.from(deps).filter(d => d !== otherName && !recursiveTypes.has(d));
        if (nonSelfDeps.every(d => visited.has(d))) {
          queue.push(otherName);
        }
      }
    }
  }

  // Append any remaining (circular dependencies handled by z.lazy)
  for (const msg of messages) {
    if (!result.includes(msg)) {
      result.push(msg);
    }
  }

  return { sortedMessages: result, recursiveTypes };
}

/**
 * Checks if there's a cycle starting from the given node
 */
function hasCycle(
  node: string,
  dependencies: Map<string, Set<string>>,
  visiting: Set<string>
): boolean {
  if (visiting.has(node)) return true;
  visiting.add(node);

  for (const dep of dependencies.get(node) ?? []) {
    if (hasCycle(dep, dependencies, visiting)) {
      return true;
    }
  }

  visiting.delete(node);
  return false;
}
