version: '3'

vars:
  GEN_DIR: gen
  PROTO_DIR: proto

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # Installation
  install:
    desc: Install npm dependencies and update buf dependencies
    cmds:
      - task: check
      - npm install
      - npx buf dep update proto
      - echo "✅ All dependencies installed successfully!"

  check:
    desc: Check if required tools are installed
    cmds:
      - |
        echo "Checking required tools..."
        echo ""

        MISSING_REQUIRED=0

        # Check required tools
        command -v node &> /dev/null && echo "✅ Node.js $(node --version)" || { echo "❌ Node.js - Install from: https://nodejs.org/"; MISSING_REQUIRED=1; }
        command -v npm &> /dev/null && echo "✅ npm $(npm --version)" || { echo "❌ npm - Install from: https://nodejs.org/"; MISSING_REQUIRED=1; }

        # Check optional tools
        command -v buf &> /dev/null && echo "✅ buf $(buf --version)" || { npx buf --version &> /dev/null 2>&1 && echo "✅ buf $(npx buf --version) (via npx)" || echo "⚠️  buf - Will use npx (optional: go install github.com/bufbuild/buf/cmd/buf@latest)"; }
        command -v go &> /dev/null && echo "✅ Go $(go version | awk '{print $3}')" || echo "⚠️  Go (optional) - Install from: https://go.dev/dl/"

        echo ""
        [ $MISSING_REQUIRED -eq 0 ] && echo "✅ All required tools are installed!" || { echo "❌ Some required tools are missing. Please install them before continuing."; exit 1; }

  # Linting
  lint:
    desc: Lint proto files with buf
    cmds:
      - npx buf lint {{.PROTO_DIR}}
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'
      - '{{.PROTO_DIR}}/buf.yaml'

  lint:buf:
    desc: Lint proto files with buf
    cmds:
      - npx buf lint {{.PROTO_DIR}}
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'
      - '{{.PROTO_DIR}}/buf.yaml'

  lint:ci:
    desc: Run all linting checks (CI mode)
    cmds:
      - task: lint
      - task: format:check

  # Formatting
  format:
    desc: Format proto files with buf
    cmds:
      - npx buf format -w
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'

  format:check:
    desc: Check if proto files are formatted (no write)
    cmds:
      - npx buf format -d --exit-code
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'

  # Breaking changes
  breaking:
    desc: Check for breaking changes against main branch
    cmds:
      - npx buf breaking --against '.git#branch=main'
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'

  breaking:verbose:
    desc: Check for breaking changes with verbose output
    cmds:
      - npx buf breaking --against '.git#branch=main' --error-format=json | jq

  # Code generation
  generate:
    desc: Generate code for all languages (Python, TypeScript)
    cmds:
      - npx buf generate
    sources:
      - '{{.PROTO_DIR}}/**/*.proto'
      - buf.gen.yaml
    generates:
      - '{{.GEN_DIR}}/**/*'

  generate:check:
    desc: Verify generated code is up to date
    cmds:
      - npx buf generate
      - |
        if [ -n "$(git status --porcelain {{.GEN_DIR}}/)" ]; then
          echo "Error: Generated code is out of date"
          echo "Run 'task generate' and commit the changes"
          exit 1
        fi

  # Buf Schema Registry
  push:
    desc: Push schema to Buf Schema Registry (requires DKIN_CLOUD_TOKEN or BUF_TOKEN)
    cmds:
      - npx buf push {{.PROTO_DIR}}
    preconditions:
      - sh: '[ ! -z "$DKIN_CLOUD_TOKEN" ] || [ ! -z "$BUF_TOKEN" ]'
        msg: 'DKIN_CLOUD_TOKEN or BUF_TOKEN environment variable must be set'

  push:tag:
    desc: "Push schema with a tag (usage: task push:tag TAG=v1.0.0)"
    cmds:
      - npx buf push {{.PROTO_DIR}} --tag {{.TAG}}
    preconditions:
      - sh: '[ ! -z "{{.TAG}}" ]'
        msg: 'TAG variable must be set (e.g., task push:tag TAG=v1.0.0)'
      - sh: '[ ! -z "$DKIN_CLOUD_TOKEN" ] || [ ! -z "$BUF_TOKEN" ]'
        msg: 'DKIN_CLOUD_TOKEN or BUF_TOKEN environment variable must be set'

  # Build workflows
  build:
    desc: Full build - format, lint, and generate
    cmds:
      - task: format
      - task: lint
      - task: generate
      - echo "✅ Build completed successfully!"

  build:ci:
    desc: CI build - format check, lint, breaking, and generate check
    cmds:
      - task: format:check
      - task: lint
      - task: breaking
      - task: generate:check

  # CI simulation
  ci:
    desc: Run all CI checks locally (format, lint, breaking, generate)
    cmds:
      - echo "Running CI checks..."
      - task: format:check
      - task: lint
      - task: breaking
      - task: generate:check
      - echo "✅ All CI checks passed!"

  # Cleanup
  clean:
    desc: Remove generated files (gen/)
    cmds:
      - rm -rf {{.GEN_DIR}}/

  clean:all:
    desc: Remove all generated and dependency files
    cmds:
      - task: clean
      - rm -rf node_modules/

  # Validation
  validate:
    desc: Validate proto files are syntactically correct
    cmds:
      - npx buf build {{.PROTO_DIR}}

  # Dependency management
  deps:
    desc: Show buf dependencies
    cmds:
      - npx buf dep ls {{.PROTO_DIR}}

  deps:update:
    desc: Update buf dependencies
    cmds:
      - npx buf dep update {{.PROTO_DIR}}

  # Development helpers
  watch:
    desc: Watch for changes and auto-generate code
    cmds:
      - |
        echo "Watching for proto file changes..."
        while true; do
          inotifywait -e modify,create,delete -r {{.PROTO_DIR}}/ && task generate
        done

  stats:
    desc: Show statistics about proto files
    cmds:
      - |
        echo "Proto File Statistics:"
        echo "======================"
        echo "Total proto files: $(find {{.PROTO_DIR}} -name '*.proto' | wc -l)"
        echo "Total services: $(grep -r 'service ' {{.PROTO_DIR}} --include='*.proto' | wc -l)"
        echo "Total messages: $(grep -r 'message ' {{.PROTO_DIR}} --include='*.proto' | wc -l)"
        echo "Total RPCs: $(grep -r 'rpc ' {{.PROTO_DIR}} --include='*.proto' | wc -l)"
        echo "Lines of proto: $(find {{.PROTO_DIR}} -name '*.proto' -exec wc -l {} + | tail -1)"
